version: '3.2'
services:
    database:
        image: postgres:12
        volumes:
            - ./data/database:/var/lib/postgresql/data
        networks:
            - directus
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: 'directus'
            POSTGRES_PASSWORD: 'directus'
            POSTGRES_DB: 'directus'

    cache:
        image: redis:6
        networks:
            - directus
        ports:
            - 6379:6379

    directus:
        image: directus/directus:v9.0.0-rc.22
        ports:
            - 8055:8055
        networks:
            - directus
        environment:
            KEY: '255d861b-5ea1-5996-9aa3-922530ec40b1'
            SECRET: '6116487b-cda1-52c2-b5b5-c8022c453123'

            DB_CLIENT: 'pg'
            DB_HOST: 'database'
            DB_PORT: '5432'
            DB_DATABASE: 'directus'
            DB_USER: 'directus'
            DB_PASSWORD: 'directus'

            CACHE_ENABLED: 'true'
            CACHE_STORE: 'redis'
            CACHE_REDIS: 'redis://cache:6379'

networks:
    directus:
